### ISSUE TITLE
Does not exit gracefully on broadcast ip

### ISSUE THREAD

**Issue by jinankjain** [mozilla/ssh_scan#161]
Suppose if we pass broadcast ip as a parameter to -t or -f ssh_scan does quit gracefully.

```
bin/ssh_scan -t 128.237.155.255
```

```
/usr/lib/ruby/2.1.0/socket.rb:54:in `connect_nonblock': Network is unreachable - connect(2) for 128.237.155.255:22 (Errno::ENETUNREACH)
	from /usr/lib/ruby/2.1.0/socket.rb:54:in `connect_internal'
	from /usr/lib/ruby/2.1.0/socket.rb:140:in `connect'
	from /usr/lib/ruby/2.1.0/socket.rb:338:in `block in tcp'
	from /usr/lib/ruby/2.1.0/socket.rb:232:in `each'
	from /usr/lib/ruby/2.1.0/socket.rb:232:in `foreach'
	from /usr/lib/ruby/2.1.0/socket.rb:328:in `tcp'
	from /home/turingmachine/GitProjects/ssh_scan/lib/ssh_scan/client.rb:21:in `connect'
	from /home/turingmachine/GitProjects/ssh_scan/lib/ssh_scan/scan_engine.rb:35:in `scan_target'
	from /home/turingmachine/GitProjects/ssh_scan/lib/ssh_scan/scan_engine.rb:113:in `block (2 levels) in scan'
```

We need better error handling for such things.

**Comment by claudijd** [comment]
Yeah, we just need some exception handling to trap and effort on that Errno::ENETUNREACH
