### ISSUE TITLE
Throwing stack traces on invalid input to ssh_scan binary

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#386]
$ ruby bin/ssh_scan -t sklep.sportprofit.pl/
/Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/netaddr-1.5.1/lib/cidr.rb:168:in `create': CIDR address is improperly formatted. Missing netmask after '/' character. (ArgumentError)
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/target_parser.rb:31:in `enumerateIPRange'
	from bin/ssh_scan:54:in `block (3 levels) in <main>'
	from bin/ssh_scan:52:in `each'
	from bin/ssh_scan:52:in `block (2 levels) in <main>'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1427:in `call'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1427:in `block in parse_in_order'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
	from bin/ssh_scan:196:in `<main>'

**Comment by claudijd** [comment]
We should handle this more sanely and pop help via binary.  Via engine, if supplied, we should generate an error inside the json saying it's an invalid target.

**Comment by claudijd** [comment]
Fixed
