### ISSUE TITLE
Argument Error when setting IP on result object

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#402]
```
$ ruby bin/ssh_scan -t www.eastspring.com.tw
/Users/jclaudius/code/ssh_scan/lib/ssh_scan/result.rb:26:in `ip=': Invalid attempt to set IP to a non-IP address value (ArgumentError)
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/result.rb:201:in `set_client_attributes'
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:51:in `scan_target'
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:176:in `block (2 levels) in scan'
```

**Comment by claudijd** [comment]
This appears to be an issue with DNS resolution....

```
$ host www.eastspring.com.tw
www.eastspring.com.tw has address 122.147.14.80
^C
```

If we use dig, it works fine, but if you run with host command it will run indefinitely

**Comment by claudijd** [comment]
If we attempt to scan with the IP directly, it will complete the scan (even though the service isn't hosting SSH).

**Comment by claudijd** [comment]
0.0.37 gets past this issue now, though I think SSH is no longer listening. I'm closing assuming it's fixed, please reopen if you can repro it still.
