### ISSUE TITLE
/usr/local/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': Invalid argument - connect(2) for [fe80::6ef0:49ff:fe7a:81b0]:22 (Errno::EINVAL)

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#415]
`
/usr/local/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': Invalid argument - connect(2) for [fe80::6ef0:49ff:fe7a:81b0]:22 (Errno::EINVAL)
	from /usr/local/lib/ruby/2.4.0/socket.rb:1198:in `connect_nonblock'
	from /usr/local/lib/ruby/2.4.0/socket.rb:56:in `connect_internal'
	from /usr/local/lib/ruby/2.4.0/socket.rb:137:in `connect'
	from /usr/local/lib/ruby/2.4.0/socket.rb:627:in `block in tcp'
	from /usr/local/lib/ruby/2.4.0/socket.rb:227:in `each'
	from /usr/local/lib/ruby/2.4.0/socket.rb:227:in `foreach'
	from /usr/local/lib/ruby/2.4.0/socket.rb:617:in `tcp'
	from /usr/local/bundle/gems/ssh_scan-0.0.27/lib/ssh_scan/client.rb:48:in `block in connect'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /usr/local/bundle/gems/ssh_scan-0.0.27/lib/ssh_scan/client.rb:47:in `connect'
	from /usr/local/bundle/gems/ssh_scan-0.0.27/lib/ssh_scan/scan_engine.rb:50:in `scan_target'
	from /usr/local/bundle/gems/ssh_scan-0.0.27/lib/ssh_scan/scan_engine.rb:176:in `block (2 levels) in scan'
`

**Comment by claudijd** [comment]
I'm guessing this is intertwined with the root cause of #472
