### ISSUE TITLE
Docker container fails with example in README

### ISSUE THREAD

**Issue by rrazor** [mozilla/ssh_scan#510]
**Steps**

1. Pull the latest container (image ID `ab59549aae7c`) from DockerHub:
        
        $ docker pull mozilla/ssh_scan
        Using default tag: latest
        latest: Pulling from mozilla/ssh_scan
        Digest: sha256:5a039264d6786d1c0841252d2990e82bced5339d1e8f23b3cb04ec1fb7655b77
        Status: Image is up to date for mozilla/ssh_scan:latest
        docker.io/mozilla/ssh_scan:latest

1. Run the example command from the `README` file:

        $ docker run -it mozilla/ssh_scan /app/bin/ssh_scan -t sshscan.rubidus.com
        Traceback (most recent call last):
               2: from /app/bin/ssh_scan:7:in `<main>'
        	1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- netaddr (LoadError)

**Expected results**
SSH scan runs and returns JSON output.

**Actual results**
See traceback above.

**Technical**
I was able to get `ssh_scan` to work by entering the container via a shell, then manually running `gem install` for each of its dependencies. I suspect something about the gem installation process is broken for the container build.

**Comment by rrazor** [comment]
Related issue from another project that depends on the upstream container:
https://github.com/ibnesayeed/linkextractor/issues/6

**Comment by rrazor** [comment]
I've filed an issue upstream:
https://github.com/docker-library/ruby/issues/305
